// Code generated by Wire protocol buffer compiler, do not edit.
// Source: squareup.geology.display_name in squareup/geology/period.proto
@file:Suppress("DEPRECATION")

package squareup.geology

import kotlin.String
import kotlin.Suppress
import kotlin.`annotation`.AnnotationRetention
import kotlin.`annotation`.AnnotationTarget
import kotlin.`annotation`.Retention
import kotlin.`annotation`.Target

@Retention(AnnotationRetention.RUNTIME)
@Target(
  AnnotationTarget.PROPERTY,
  AnnotationTarget.FIELD,
)
public annotation class DisplayNameOption(
  public val `value`: String,
)
