// Code generated by Wire protocol buffer compiler, do not edit.
// Source: squareup.geology.Period in squareup/geology/period.proto
@file:Suppress("DEPRECATION")

package squareup.geology

import com.squareup.wire.EnumAdapter
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.Syntax.PROTO_2
import com.squareup.wire.WireEnum
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.JvmStatic
import kotlin.Int
import kotlin.Suppress

public enum class Period(
  override val `value`: Int,
) : WireEnum {
  @DisplayNameOption("Cre taceous")
  CRETACEOUS(1),
  @DisplayNameOption("Jurassic 2025")
  JURASSIC(2),
  @DisplayNameOption("Triage")
  TRIASSIC(3),
  ;

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<Period> = object : EnumAdapter<Period>(
      Period::class, 
      PROTO_2, 
      null
    ) {
      override fun fromValue(`value`: Int): Period? = Period.fromValue(`value`)
    }

    @JvmStatic
    public fun fromValue(`value`: Int): Period? = when (`value`) {
      1 -> CRETACEOUS
      2 -> JURASSIC
      3 -> TRIASSIC
      else -> null
    }
  }
}
